excluded:
  - Pods/
  - Carthage/
  - dev-testTests/
  - dev-testUITests/

#デフォルト無効のルールのうち、有効にするもの。
opt_in_rules:
  - anyobject_protocol #Classのみのプロトコルでは、classよりもAnyObjectを使用することをお勧めします
  - array_init #sequenceからArrayへの変換をする際に、seq.map { $0 }ではなくArray(seq)を使用する方が望ましいというもの。
  - attributes # @objcや@IBOutletなどの属性(attributes)はvarやimportに対するものの場合は同じ行に配置し、型や関数に対するものの場合は別の行に配置すべきというもの。
  - closure_end_indentation # クロージャーの最後の閉じ括弧はクロージャーの先頭の行のインデントに揃えるべきというもの。
  - closure_spacing # クロージャーの式を記述する際に、中括弧の中の始まりと終わりの部分に１つだけスペースを入れるべきというもの。
  - collection_alignment # コレクションリテラルのすべての要素は、垂直方向に配置する必要があります
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition
